enum QmageDecoderError {
    QM_DEC_ANI_END_OF_FRAME = 0,
    QM_DEC_ANI_NOT_ENOUGH_DATA = -10,
    QM_DEC_ANI_FAIL = -9,
    QM_DEC_INVALID_SIZE = -8,
    QM_DEC_INVALID_ADDRESS = -7,
    QM_DEC_OUT_OF_MEMORY = -6,
    QM_DEC_UNSUPPORTED_VERSION = -5,
    QM_DEC_UNSUPPORTED_TYPE = -4,
    QM_DEC_UNSUPPORTED_FILE = -3,
    QM_DEC_CORRUPTED_FILE = -2,
    QM_DEC_FAIL = -1
};
