enum QmageDecoderError {
    QM_DEC_ANI_END_OF_FRAME,
    QM_DEC_ANI_NOT_ENOUGH_DATA,
    QM_DEC_ANI_FAIL,
    QM_DEC_INVALID_SIZE,
    QM_DEC_INVALID_ADDRESS,
    QM_DEC_OUT_OF_MEMORY,
    QM_DEC_UNSUPPORTED_VERSION,
    QM_DEC_UNSUPPORTED_TYPE,
    QM_DEC_UNSUPPORTED_FILE,
    QM_DEC_CORRUPTED_FILE,
    QM_DEC_FAIL
};