enum QmageDecodeCodecType {
    QMAGE_DEC_V16_SHORT_INDEX,
    QMAGE_DEC_W2_PASS,
    QMAGE_DEC_V16_BYTE_INDEX,
    QMAGE_DEC_W1_PASS,
    QMAGE_DEC_FCODEC,
    QMAGE_DEC_W1_PASS_FROM_W_ADAPTIVE,
    QMAGE_DEC_V24_SHORT_INDEX,
    QMAGE_DEC_W2_PASS_ONLY,
    QMAGE_DEC_PV,
    QMAGE_DEC_SLV,
    QMAGE_DEC_QV
};